# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  test-backend-4:
    build:
      target: development
    image: test-backend-4-development
    container_name: test-backend-4-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
