services:
  test-backend-4:
    build:
      context: .
      target: production
    image: test-backend-4
    container_name: test-backend-4
    depends_on:
      - test-backend-4-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: test-backend-4-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}

  test-backend-4-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: test-backend-4
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
